version: "3.8"
services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    volumes:
      - minio_data:/data
    ports:
      - "${DOCKER_MINIO_API_PORT:-9000}:9000"      # S3 API
      - "${DOCKER_MINIO_CONSOLE_PORT:-9001}:9001"  # Console
    command: server /data --console-address ":9001"
    restart: unless-stopped
    env_file:
      - ../.env

volumes:
  minio_data:
